# ansible/roles/ssl/tasks/main.yml
---
- name: Add Caddy repository
  shell: |
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list

- name: Install Caddy
  apt:
    name: caddy
    update_cache: yes
    state: present

- name: Configure Caddy
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: '0644'

- name: Restart Caddy
  systemd:
    name: caddy
    state: restarted
    enabled: yes