---
- name: Install Python packages
  pip:
    name:
      - flask
      - flask-limiter
      - requests
    state: present

- name: Create service directory
  file:
    path: /opt/wg_service
    state: directory
    mode: '0755'

- name: Create security log file with proper permissions
  file:
    path: /opt/wg_service/security.log
    state: touch
    mode: '0600'
    owner: root
    group: root

- name: Copy WireGuard service script
  template:
    src: wg_server.py.j2
    dest: "{{ wg_service_dir }}/wg_server.py"
    mode: '0755'

- name: Create used IPs file with secure permissions
  file:
    path: /opt/wg_service/used_ips.json
    state: touch
    mode: '0600'
    owner: root
    group: root

- name: Create systemd service file
  template:
    src: wg_service.service.j2
    dest: /etc/systemd/system/wg_service.service
    mode: '0644'

- name: Generate client setup script
  template:
    src: client_setup.py.j2
    dest: "{{ wg_service_dir }}/client_setup.py"
    mode: '0755'
  vars:
    wireguard_server_url: "http://{{ ansible_host }}:{{ wg_service_port }}" # Server URL

- name: Start and enable WG service
  systemd:
    name: wg_service
    state: started
    enabled: yes
    daemon_reload: yes
